export const COLOMBIA_CITIES = [
    "Bogotá D.C.",
    "Medellín",
    "Cali",
    "Barranquilla",
    "Cartagena de Indias",
    "Soacha",
    "Cúcuta",
    "Soledad",
    "Bucaramanga",
    "Bello",
    "Villavicencio",
    "Ibagué",
    "Santa Marta",
    "Valledupar",
    "Manizales",
    "Pereira",
    "Montería",
    "Neiva",
    "Pasto",
    "Armenia",
    "Riohacha",
    "Sincelejo",
    "Popayán",
    "Tunja",
    "Fusagasugá",
    "Yopal",
    "Florencia",
    "Quibdó",
    "Palmira",
    "Buenaventura",
    "Barrancabermeja",
    "Girardot",
    "Duitama",
    "Sogamoso",
    "Facatativá",
    "Zipaquirá",
    "Chía",
    "Mosquera",
    "Madrid",
    "Funza",
    "Rionegro",
    "Envigado",
    "Itagüí",
    "Apartadó",
    "Tuluá",
    "Buga",
    "Cartago",
    "Jamundí",
    "Yumbo",
    "Ipiales",
    "Tumaco",
    "Magangué",
    "Maicao",
    "Uribia",
    "Piedecuesta",
    "Girón",
    "Floridablanca",
    "Malambo",
    "Sabanalarga",
    "Ciénaga",
    "Ocaña",
    "Villa del Rosario",
    "Los Patios",
    "Arauca",
    "Mocóa",
    "Leticia",
    "San Andrés",
    "Inírida",
    "San José del Guaviare",
    "Mitú",
    "Puerto Carreño"
].sort();
