export const PRODUCT_CATEGORIES = [
    { id: "Abarrotes", icon: "grocery", color: "orange" },
    { id: "Bebidas", icon: "local_drink", color: "blue" },
    { id: "Lácteos", icon: "nutrition", color: "cyan" },
    { id: "Snacks", icon: "cookie", color: "purple" },
    { id: "Aseo", icon: "cleaning_services", color: "teal" },
    { id: "Cuidado Personal", icon: "face", color: "rose" },
    { id: "Panadería", icon: "bakery_dining", color: "amber" },
    { id: "Frutas y Verduras", icon: "eco", color: "green" },
    { id: "Carnes y Pescados", icon: "set_meal", color: "red" },
    { id: "Licores", icon: "liquor", color: "indigo" },
    { id: "Mascotas", icon: "pets", color: "brown" },
    { id: "Bebés", icon: "child_care", color: "pink" },
    { id: "Congelados", icon: "ac_unit", color: "sky" },
    { id: "Hogar", icon: "chair", color: "slate" },
    { id: "Farmacia", icon: "medication", color: "red" },
    { id: "Papelería", icon: "school", color: "yellow" },
    { id: "Tecnología", icon: "devices", color: "gray" },
    { id: "Automotriz", icon: "directions_car", color: "zinc" },
    { id: "Cigarrillos", icon: "smoking_rooms", color: "stone" },
    { id: "Otros", icon: "category", color: "slate" },
];
